# the following parameters are the same across the project and might be needed in more than one module #
root_dir: "/sc-atac-seq" # path to the main dir of the project where GitHub repo lives
data_dir: "/sc-atac-seq/analyses/cellranger-analysis/results/02_cellranger_count/DefaultParameters" # path to data dir of the project with CellRanger output results
metadata_dir: "/data/project_metadata" # path to metadata dir of the project
genome_name: "GRCm39" # define genome reference and versioning. Options: (1) human: "GRCh38"; (2) mouse: "GRCm39" and "mm10"; and (3) dual index genomes: "GRCh38ANDGRCm39" and "GRCh38_mm10".
PROJECT_NAME: "Victoria_Knockout - Testing cohort"
PI_NAME: "Michael A. Dyer, PhD"
TASK_ID: "NA"
PROJECT_LEAD_NAME: "NA"
DEPARTMENT: "Developmental Neurobiology"
LEAD_ANALYSTS: "Antonia Chroni, PhD"
GROUP_LEAD: "Cody A. Ramirez, PhD"
CONTACT_EMAIL: "antonia.chroni@stjude.org"
PIPELINE: "Standard scATAC-Seq Analysis in 10X Genomics data"
START_DATE: "NA"
COMPLETION_DATE: "ONGOING"

# the following parameters are set up as default values and/or are specific for the following modules: 
# `./analyses/fastqc-analysis`
# FASTQ paths to the fastqc files with format: `path1/*R1-R3*.fastq.gz` are extracted from the `metadata_dir`.
# No need to manually define variables

# `./analyses/cellranger-analysis`
genome_reference_path: "./reference_genomes/cellranger-sc-atac-seq/2020-A/mus_musculus/mm10/downloads/refdata-cellranger-arc-mm10-2020-A-2.0.0" #path to genome reference to be used for the `cellranger-analysis` module
cellranger_parameters: "DefaultParameters" # or "ForcedCells8000Parameters" etc
genome_name_cellranger: "GRCm39" #please define the genome of preference for dual genomes. In case for single genomes, please use the same as used for `genome_name`.
sample_prefix: "DYE"  # define the prefix with the Sample ID used for the samples of the project. This requires that all of the Sample IDs are the same, e.g., DYE001, DYE002, DYE003 and so on.

# `./analyses/upstream-analysis`
